services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.6.4
    container_name: homeassistant
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./containers/config:/config
      - ../custom_components/ha_ragent:/config/custom_components/ha_ragent

  ollama:
    image: ollama/ollama:0.24.0
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./containers/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mongo:
    image: mongodb/mongodb-atlas-local:7.0.9
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - ./containers/mongodb/db:/data/db
      - ./containers/mongodb/config:/data/configdb

  chromadb:
    image: chromadb/chroma:1.5.5
    container_name: chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./containers/chromadb:/data