services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.9.0
    container_name: homeassistant
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./containers/config:/config
      - ../custom_components/ha_ragent:/config/custom_components/ha_ragent

  ollama:
    image: ollama/ollama:0.33.2
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./containers/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b10818
    container_name: llamacpp
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./containers/llamacpp:/models
    environment:
      LLAMA_CACHE: /models/cache
    command:
      - --hf-repo
      - Qwen/Qwen3-1.7B-GGUF:Q8_0
      - --parallel
      - "1"
      - --ubatch-size
      - "1024"
      - --ctx-size
      - "8192"
      - --host
      - 0.0.0.0
      - --port
      - "8080"

  llamacpp_embed:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b10818
    container_name: llamacpp_embed
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./containers/llamacpp_embed:/models
    environment:
      LLAMA_CACHE: /models/cache
    command:
      - --hf-repo
      - nomic-ai/nomic-embed-text-v1.5-GGUF:Q4_K_M
      - --embeddings
      - --parallel
      - "1"
      - --ubatch-size
      - "1024"
      - --ctx-size
      - "2048"
      - --host
      - 0.0.0.0
      - --port
      - "8080"

  mongo:
    image: mongodb/mongodb-atlas-local:7.0.9
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - ./containers/mongodb/db:/data/db
      - ./containers/mongodb/config:/data/configdb

  chromadb:
    image: chromadb/chroma:1.5.5
    container_name: chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./containers/chromadb:/data
